services:

  app:
    image: ghcr.io/sopheaklaing/infraflow:${APP_TAG}
    container_name: infraflow

    ports:
      - "127.0.0.1:8080:8080"

    restart: unless-stopped

    security_opt:
      - no-new-privileges:true

    cap_drop:
      - ALL

    read_only: true

    tmpfs:
      - /tmp

    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:8080/api/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

  prometheus:
    image: prom/prometheus:v3.8.1
    container_name: infraflow-prometheus

    ports:
      - "127.0.0.1:9090:9090"

    restart: unless-stopped

    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus

  grafana:
    image: grafana/grafana:12.1.1
    container_name: infraflow-grafana

    ports:
      - "127.0.0.1:3000:3000"

    restart: unless-stopped

    volumes:
      - grafana-data:/var/lib/grafana

  node-exporter:
    image: prom/node-exporter:v1.10.2
    container_name: infraflow-node-exporter

    restart: unless-stopped

    pid: host

    command:
      - "--path.procfs=/host/proc"
      - "--path.sysfs=/host/sys"
      - "--path.rootfs=/host"

    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/host:ro,rslave

volumes:
  prometheus-data:
  grafana-data: